
# Parameters for the example pipeline. Feel free to delete these once you
# remove the example pipeline from pipeline.py and the example nodes in
# `src/pipelines/`
n_splits: 5
n_calls: 40
epochs: 200
test_data_ratio: 0.2

